### ISSUE TITLE
Cannot follow 307/308 HTTP redirects in verbose mode if request body is being streamed

### ISSUE THREAD

**Issue by ducaale** [httpie/httpie#1079]
**Checklist**

- [x] I've searched for similar issues.
- [x] I'm using the the latest version of HTTPie.

---

**What are the steps to reproduce the problem?**

1. Create a file with some content `echo 'hello world' | file.txt`
2. Run ` http --follow -v post pie.dev/redirect-to url==https://pie.dev/post status_code==307 @file.txt`

**What is the expected result?**

HTTPie should be able to follow any 307/308 HTTP redirect and print intermediate requests/responses.

**What happens instead?**

HTTPie hangs for a while before throwing a connection error

**Debug output**

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```
$ http --follow -v --debug post pie.dev/redirect-to url==https://pie.dev/post status_code==307 @cli-tools-i-use.txt
HTTPie 2.4.0
Requests 2.22.0
Pygments 2.7.2
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0]
/usr/bin/python3
Linux 4.19.104-microsoft-standard

<Environment {'colors': 256,
 'config': {'__meta__': {'about': 'HTTPie configuration file',
                         'help': 'https://httpie.org/doc#config',
                         'httpie': '1.0.3'},
            'default_options': []},
 'config_dir': PosixPath('/home/ducaale/.httpie'),
 'devnull': <property object at 0x7fd43892b720>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x7fd43892cd30>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

>>> requests.request(**{'auth': None,
 'data': <_io.BufferedReader name='cli-tools-i-use.txt'>,
 'headers': {'User-Agent': b'HTTPie/2.4.0', 'Accept': b'application/json, */*;q=0.5', 'Content-Type': b'text/plain'},
 'method': 'post',
 'params': <generator object MultiValueOrderedDict.items at 0x7fd4388a2a50>,
 'url': 'http://pie.dev/redirect-to'})

POST /redirect-to?url=https%3A%2F%2Fpie.dev%2Fpost&status_code=307 HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 66
Content-Type: text/plain
Host: pie.dev
User-Agent: HTTPie/2.4.0

fzf
neovim
qrcp
zsh + oh-my-zsh
httpie
z
rg
fd
ngrok
fx


HTTP/1.1 307 TEMPORARY REDIRECT
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
CF-Cache-Status: DYNAMIC
CF-RAY: 6570761c4aafe66c-LHR
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Sat, 29 May 2021 14:37:33 GMT
Location: https://pie.dev/post
NEL: {"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=MAo3fMIpkLfAG1SJTZeG098dszmnqpVHiIFJqNq6WagAl3CdBhjEY%2FlQJjjL%2FWYPTOKaE3bXt9BUnz8gQhInnIrF%2BSrlDldlFU5NJKqDI1g8%2B6K%2Bug%3D%3D"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Transfer-Encoding: chunked
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cf-request-id: 0a5a2825b10000e66c1d97d000000001




POST /post HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 66
Content-Type: text/plain
Host: pie.dev
User-Agent: HTTPie/2.4.0





http: error: ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')")) while doing a POST request to URL: https://pie.dev/post

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ducaale/.local/bin/http", line 8, in <module>
    sys.exit(main())
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/__main__.py", line 11, in main
    exit_status = main()
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/core.py", line 70, in main
    exit_status = program(
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/core.py", line 169, in program
    for message in messages:
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/client.py", line 101, in collect_messages
    response = requests_session.send(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))
```

**Provide any additional information, screenshots, or code examples below:**
N/A

**Comment by ducaale** [comment]
A similar thing happens for multipart requests but I am not sure If I should open a separate issue for it

```
$ http --follow -v -f --debug post pie.dev/redirect-to url==https://pie.dev/post status_code==307 file@cli-tools-i-use.txt
HTTPie 2.4.0
Requests 2.22.0
Pygments 2.7.2
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0]
/usr/bin/python3
Linux 4.19.104-microsoft-standard

<Environment {'colors': 256,
 'config': {'__meta__': {'about': 'HTTPie configuration file',
                         'help': 'https://httpie.org/doc#config',
                         'httpie': '1.0.3'},
            'default_options': []},
 'config_dir': PosixPath('/home/ducaale/.httpie'),
 'devnull': <property object at 0x7fd44131e6d0>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x7fd44131fd30>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

>>> requests.request(**{'auth': None,
 'data': <MultipartEncoder: <generator object MultiValueOrderedDict.items at 0x7fd441295a50>>,
 'headers': {'User-Agent': b'HTTPie/2.4.0', 'Content-Type': 'multipart/form-data; boundary=946097438161446cb3d9922d420dcec1'},
 'method': 'post',
 'params': <generator object MultiValueOrderedDict.items at 0x7fd441295ba0>,
 'url': 'http://pie.dev/redirect-to'})

POST /redirect-to?url=https%3A%2F%2Fpie.dev%2Fpost&status_code=307 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 247
Content-Type: multipart/form-data; boundary=946097438161446cb3d9922d420dcec1
Host: pie.dev
User-Agent: HTTPie/2.4.0

--946097438161446cb3d9922d420dcec1
Content-Disposition: form-data; name="file"; filename="cli-tools-i-use.txt"
Content-Type: text/plain

fzf
neovim
qrcp
zsh + oh-my-zsh
httpie
z
rg
fd
ngrok
fx

--946097438161446cb3d9922d420dcec1--


HTTP/1.1 307 TEMPORARY REDIRECT
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
CF-Cache-Status: DYNAMIC
CF-RAY: 65708df1dcf806bd-LHR
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Sat, 29 May 2021 14:53:49 GMT
Location: https://pie.dev/post
NEL: {"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=ZyPkFYRlmMqcuQM0aEYxoig1yVzMfUlojF8GSiiWstft4KfAwMsUwy2urtcRiefDEyVWqWZeskR1barr0JeUPjkgx%2BMnTbKKEu63uyyh8er1%2FVE8VQ%3D%3D"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Transfer-Encoding: chunked
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cf-request-id: 0a5a370b24000006bd22a95000000001




POST /post HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 247
Content-Type: multipart/form-data; boundary=946097438161446cb3d9922d420dcec1
Host: pie.dev
User-Agent: HTTPie/2.4.0


http: error: TypeError: argument of type 'MultipartEncoder' is not iterable

Traceback (most recent call last):
  File "/home/ducaale/.local/bin/http", line 8, in <module>
    sys.exit(main())
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/__main__.py", line 11, in main
    exit_status = main()
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/core.py", line 70, in main
    exit_status = program(
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/core.py", line 190, in program
    write_message(requests_message=message, env=env, args=args, with_headers=with_headers,
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/output/writer.py", line 44, in write_message
    write_stream(**write_stream_kwargs)
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/output/writer.py", line 66, in write_stream
    for chunk in stream:
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/output/writer.py", line 108, in build_output_stream_for_message
    yield from stream_class(
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/output/streams.py", line 65, in __iter__
    for chunk in self.iter_body():
  File "/home/ducaale/.local/lib/python3.8/site-packages/httpie/output/streams.py", line 190, in iter_body
    if not converter and b'\0' in chunk:
TypeError: argument of type 'MultipartEncoder' is not iterable
```

**Comment by BoboTiG** [comment]
Thanks for the detailled report @ducaale :)

I was able to reproduce the issue and will work on a patch shortly.

**Comment by BoboTiG** [comment]
@ducaale the original issue has been fixed in master :champagne:

**Comment by BoboTiG** [comment]
(The second issue, if still revelant, should have its own issue.)
