### ISSUE TITLE
TypeError when printing response headers

### ISSUE THREAD

**Issue by andrascz** [httpie/httpie#1180]
## Checklist

- [x] I've searched for similar issues.
- [x] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

1. `http -h https://www.google.com`

## Current result

```
http: error: TypeError: sequence item 0: expected str instance, bytes found
```

## Expected result

the response headers printed

---

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```bash
$ http --debug -h https://www.google.com
HTTPie 2.5.0
Requests 2.26.0
Pygments 2.10.0
Python 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0]
/usr/bin/python3
Linux 5.14.9-arch2-1

<Environment {'colors': 256,
 'config': {'__meta__': {'about': 'HTTPie configuration file',
                         'help': 'https://httpie.org/doc#config',
                         'httpie': '1.0.3'},
            'default_options': []},
 'config_dir': PosixPath('/home/user/.httpie'),
 'devnull': <property object at 0x7f6ace559c20>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x7f6ace433280>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

>>> requests.request(**{'auth': None,
 'data': RequestJSONDataDict(),
 'headers': {'User-Agent': b'HTTPie/2.5.0'},
 'method': 'get',
 'params': <generator object MultiValueOrderedDict.items at 0x7f6acddc6ac0>,
 'url': 'https://www.google.com'})


http: error: TypeError: sequence item 0: expected str instance, bytes found

Traceback (most recent call last):
  File "/usr/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie==2.5.0', 'console_scripts', 'http')())
  File "/usr/lib/python3.9/site-packages/httpie/__main__.py", line 9, in main
    exit_status = main()
  File "/usr/lib/python3.9/site-packages/httpie/core.py", line 70, in main
    exit_status = program(
  File "/usr/lib/python3.9/site-packages/httpie/core.py", line 190, in program
    write_message(requests_message=message, env=env, args=args, with_headers=with_headers,
  File "/usr/lib/python3.9/site-packages/httpie/output/writer.py", line 44, in write_message
    write_stream(**write_stream_kwargs)
  File "/usr/lib/python3.9/site-packages/httpie/output/writer.py", line 66, in write_stream
    for chunk in stream:
  File "/usr/lib/python3.9/site-packages/httpie/output/writer.py", line 108, in build_output_stream_for_message
    yield from stream_class(
  File "/usr/lib/python3.9/site-packages/httpie/output/streams.py", line 62, in __iter__
    yield self.get_headers()
  File "/usr/lib/python3.9/site-packages/httpie/output/streams.py", line 143, in get_headers
    self.msg.headers).encode(self.output_encoding)
  File "/usr/lib/python3.9/site-packages/httpie/models.py", line 74, in headers
    headers.extend(
  File "/usr/lib/python3.9/site-packages/httpie/models.py", line 75, in <genexpr>
    ': '.join(header)
TypeError: sequence item 0: expected str instance, bytes found
```

## Additional information, screenshots, or code examples

My suspicion based on the stack trace is that something funky happens when multiple `Set-Cookie` headers are received.
`http -h http://www.google.com` works but it sets a single cookie for me, checking the HTTPS variant of the same page in Chrome Dev Tools shows multiple `Set-Cookie` headers in theresponse:
```
➜ http -h http://www.google.com 
HTTP/1.1 200 OK
Cache-Control: private, max-age=0
Content-Encoding: gzip
Content-Length: 6356
Content-Type: text/html; charset=ISO-8859-1
Date: Tue, 12 Oct 2021 10:59:42 GMT
Expires: -1
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Server: gws
Set-Cookie: NID=[redacted]; expires=Wed, 13-Apr-2022 10:59:42 GMT; path=/; domain=.google.com; HttpOnly
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0
```

**Comment by andrascz** [comment]
Sorry for the late response, here it is:
```
➜ http --debug -h https://google.com
HTTPie 2.7.0.dev0
Requests 2.26.0
Pygments 2.10.0
Python 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0]
/usr/bin/python3
Linux 5.14.11-arch1-1

<Environment {'colors': 256,
 'config': {'__meta__': {'about': 'HTTPie configuration file',
                         'help': 'https://httpie.org/doc#config',
                         'httpie': '1.0.3'},
            'default_options': []},
 'config_dir': PosixPath('/home/ras/.httpie'),
 'devnull': <property object at 0x7f5667976ea0>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x7f566797f310>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

<PluginManager {'adapters': [<class 'httpie_http2.HTTP2TransportPlugin'>],
 'auth': [<class 'httpie.plugins.builtin.BasicAuthPlugin'>,
          <class 'httpie.plugins.builtin.DigestAuthPlugin'>,
          <class 'httpie_jwt_auth.JWTAuthPlugin'>],
 'converters': [],
 'formatters': [<class 'httpie.output.formatters.headers.HeadersFormatter'>,
                <class 'httpie.output.formatters.json.JSONFormatter'>,
                <class 'httpie.output.formatters.xml.XMLFormatter'>,
                <class 'httpie.output.formatters.colors.ColorFormatter'>]}>

>>> requests.request(**{'auth': None,
 'data': RequestJSONDataDict(),
 'headers': <RequestHeadersDict('User-Agent': b'HTTPie/2.7.0.dev0')>,
 'method': 'get',
 'params': <generator object MultiValueOrderedDict.items at 0x7f56672a0d60>,
 'url': 'https://google.com'})


http: error: TypeError: sequence item 0: expected str instance, bytes found

Traceback (most recent call last):
  File "/usr/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie==2.6.0', 'console_scripts', 'http')())
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/__main__.py", line 9, in main
    exit_status = main()
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/core.py", line 70, in main
    exit_status = program(
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/core.py", line 190, in program
    write_message(requests_message=message, env=env, args=args, with_headers=with_headers,
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/output/writer.py", line 44, in write_message
    write_stream(**write_stream_kwargs)
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/output/writer.py", line 66, in write_stream
    for chunk in stream:
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/output/writer.py", line 109, in build_output_stream_for_message
    yield from stream_class(
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/output/streams.py", line 62, in __iter__
    yield self.get_headers()
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/output/streams.py", line 150, in get_headers
    self.msg.headers).encode(self.output_encoding)
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/models.py", line 68, in headers
    headers.extend(
  File "/home/ras/.local/lib/python3.9/site-packages/httpie/models.py", line 69, in <genexpr>
    ': '.join(header)
TypeError: sequence item 0: expected str instance, bytes found

```

**Comment by jakubroztocil** [comment]
@andrascz thanks for the debug output. I see you have `httpie-http2` installed amd that might be the cause. This plugin is obsolete (we don’t have a replacement yes). So `pip uninstall httpie-http2` should fix the issue.

**Comment by andrascz** [comment]
@jakubroztocil thank you for the suggestion. It resolved this issue.
