### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

### ISSUE THREAD

**Issue by Kirill** [httpie/httpie#1270]
## Checklist

- [*] I've searched for similar issues.
- [*] I'm using the latest version of HTTPie.

---

## Minimal reproduction code and steps

Call https drwg.ru

## Current result

![image](https://user-images.githubusercontent.com/302940/150362839-c8b17436-745c-42af-956b-8998887deb55.png)

## Expected result

![image](https://user-images.githubusercontent.com/302940/150363226-7b3f94fe-1fcf-43c4-a4e4-c7862c7baf41.png)

---

## Debug output

Please re-run the command with `--debug`, then copy the entire command & output and paste both below:

```bash
https --debug -F drwg.ru
HTTPie 2.6.0
Requests 2.26.0
Pygments 2.10.0
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
D:\Python310\python.exe
Windows 10

<Environment {'colors': 256,
 'config': {'default_options': []},
 'config_dir': WindowsPath('C:/Users/kkrasnov/AppData/Roaming/httpie'),
 'devnull': <property object at 0x00000232C296B150>,
 'is_windows': True,
 'log_error': <function Environment.log_error at 0x00000232C29B1750>,
 'program_name': 'https',
 'stderr': <colorama.ansitowin32.StreamWrapper object at 0x00000232C2984C70>,
 'stderr_isatty': True,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <colorama.ansitowin32.StreamWrapper object at 0x00000232C2984610>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': True}>

<PluginManager {'adapters': [],
 'auth': [<class 'httpie.plugins.builtin.BasicAuthPlugin'>,
          <class 'httpie.plugins.builtin.DigestAuthPlugin'>],
 'converters': [],
 'formatters': [<class 'httpie.output.formatters.headers.HeadersFormatter'>,
                <class 'httpie.output.formatters.json.JSONFormatter'>,
                <class 'httpie.output.formatters.xml.XMLFormatter'>,
                <class 'httpie.output.formatters.colors.ColorFormatter'>]}>

>>> requests.request(**{'auth': None,
 'data': RequestJSONDataDict(),
 'headers': {'User-Agent': b'HTTPie/2.6.0'},
 'method': 'get',
 'params': <generator object MultiValueOrderedDict.items at 0x00000232C2A22B20>,
 'url': 'https://drwg.ru'})


https: error: SSLError: HTTPSConnectionPool(host='drwg.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))) while doing a GET request to URL: https://drwg.ru/

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\Python310\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "D:\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\Python310\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drwg.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python310\Scripts\https.exe\__main__.py", line 7, in <module>
  File "D:\Python310\lib\site-packages\httpie\__main__.py", line 9, in main
    exit_status = main()
  File "D:\Python310\lib\site-packages\httpie\core.py", line 70, in main
    exit_status = program(
  File "D:\Python310\lib\site-packages\httpie\core.py", line 169, in program
    for message in messages:
  File "D:\Python310\lib\site-packages\httpie\client.py", line 102, in collect_messages
    response = requests_session.send(
  File "D:\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python310\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='drwg.ru', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
```

**Comment by isidentical** [comment]
Hey @Kirill!

I can reproduce the problem through `https`, though it also fails with `cURL`:
```
 $ curl -L https://drwg.ru                                                                                   1,011s

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Do you have any additional environment variables, or any custom certificates that you are using with cURL that might be missing on my local environment?

**Comment by Kirill** [comment]
Yes. I see this problem from server outside home. Strange... I generate SSL with ACME. I understand that problem with hosting. Sorry for take your time.

**Comment by isidentical** [comment]
No problems at all!
