### ISSUE TITLE
Arch Linux package doesn't install dependencies

### ISSUE THREAD

**Issue by Wizhi** [httpie/httpie#985]
Installling `httpie` from the official Arch repository doesn't seem to install the neccessary dependencies - specifically `requests-toolbelt>=0.9.1`.

```
~
❯ sudo pacman -S httpie
resolving dependencies...
looking for conflicting packages...

Packages (1) httpie-2.3.0-1

Total Installed Size:  0,48 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                        [#################################################] 100%
(1/1) checking package integrity                                                      [#################################################] 100%
(1/1) loading package files                                                           [#################################################] 100%
(1/1) checking for file conflicts                                                     [#################################################] 100%
(1/1) checking available disk space                                                   [#################################################] 100%
:: Processing package changes...
(1/1) installing httpie                                                               [#################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

~
❯ http
Traceback (most recent call last):
  File "/usr/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie==2.3.0', 'console_scripts', 'http')())
  File "/usr/lib/python3.8/site-packages/httpie/__main__.py", line 10, in main
    from .core import main
  File "/usr/lib/python3.8/site-packages/httpie/core.py", line 16, in <module>
    from httpie.client import collect_messages
  File "/usr/lib/python3.8/site-packages/httpie/client.py", line 15, in <module>
    from httpie.plugins.registry import plugin_manager
  File "/usr/lib/python3.8/site-packages/httpie/plugins/registry.py", line 1, in <module>
    from httpie.plugins.manager import PluginManager
  File "/usr/lib/python3.8/site-packages/httpie/plugins/manager.py", line 5, in <module>
    from pkg_resources import iter_entry_points
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests-toolbelt>=0.9.1' distribution was not found and is required by httpie
```

I'm not super familiar with Python, but as far as I know, packages are handled using `pip` (or `pip3`). After installing, `requests-toolbelt` also doesn't seem to appear in the `pip3 list` output.

```
~
~
❯ pip3 list | grep requests-toolbelt

~
❯
```

Installing `httpie` using `pip3 install` seems to install all dependencies correctly.

```
❯ sudo pacman -Rns httpie
checking dependencies...

Packages (1) httpie-2.3.0-1

Total Removed Size:  0,48 MiB

:: Do you want to remove these packages? [Y/n]
:: Processing package changes...
(1/1) removing httpie                                                                 [#################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

~
❯ pip3 install httpie
Defaulting to user installation because normal site-packages is not writeable
Collecting httpie
  Using cached httpie-2.3.0-py3-none-any.whl (74 kB)
Collecting requests-toolbelt>=0.9.1
  Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Requirement already satisfied: requests[socks]>=2.22.0 in /usr/lib/python3.8/site-packages (from httpie) (2.24.0)
Requirement already satisfied: Pygments>=2.5.2 in /usr/lib/python3.8/site-packages (from httpie) (2.7.2)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.8/site-packages (from requests[socks]>=2.22.0->httpie) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.8/site-packages (from requests[socks]>=2.22.0->httpie) (2.10)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.8/site-packages (from requests[socks]>=2.22.0->httpie) (1.25.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in ./.local/lib/python3.8/site-packages (from requests[socks]>=2.22.0->httpie) (1.7.1)
Installing collected packages: requests-toolbelt, httpie
Successfully installed httpie-2.3.0 requests-toolbelt-0.9.1

~
❯ pip3 list | grep requests-toolbelt
requests-toolbelt   0.9.1
```

Uninstalling `httpie` using `pip3`, and then installing it again using `pacman`, the dependency seems to persist - I'm guessing `pip3` doesn't remove dependencies automatically.

The above solved the issue for me, but I'm unsure if this is the expected behaviour or not, so I'm opening this issue.

Also, thanks a ton to all maintaners, this tool is great. :)

**Comment by Wizhi** [comment]
I see this was already reported on the Arch bug tracker[0], so I'll close this here.

Sorry about that.

[0]: https://bugs.archlinux.org/task/68472?project=5&string=httpie
