### ISSUE TITLE
version check error running on a VM bitnami LAMP AWS Server

### ISSUE THREAD

**Issue by inglesuniversal** [httpie/httpie#987]
$ http --help
Traceback (most recent call last):
  File "/usr/bin/http", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'httpie==0.9.2' distribution was not found and is required by the application

**Comment by jakubroztocil** [comment]
@inglesuniversal I’d recommend reinstalling HTTPie via `pip` manually.
