### ISSUE TITLE
ValueError: Elements in iterable body must be bytestrings

### ISSUE THREAD

**Issue by ab-kily** [httpie/httpie#995]
Hello! Thank you for such a great tool! 

I'm experiencing with an error trying to send request to API server. It seems the request is OK, but there is a problem with response - HTTPie can't parse it. Here is an example:

```shell
~$ http --print hbHB POST 'https://cloud.roistat.com/api/v1/project/analytics/data?project=48526&key=XXX' dimensions:='["marker_level_1"]' period:='{"from": "2020-10-01","to": "2020-11-01"}' metrics:='["visits"]'
POST /api/v1/project/analytics/data?project=48526&key=XXX HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 111
Content-Type: application/json
Host: cloud.roistat.com
User-Agent: HTTPie/2.3.0

{
    "dimensions": [
        "marker_level_1"
    ],
    "metrics": [
        "visits"
    ],
    "period": {
        "from": "2020-10-01",
        "to": "2020-11-01"
    }
}

http: error: ValueError: Elements in iterable body must be bytestrings. Illegal element: {
```
I've emulated request to API server using CURL, and the response is:
```shell
$ curl -i -X POST -H "Content-Type: application/json" -d @json.json 'https://cloud.roistat.com/api/v1/project/analytics/data?project=48526&key=XXX'
HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Fri, 20 Nov 2020 07:12:08 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Cache-Control: no-cache, must-revalidate
Vary: Accept-Encoding
X-Powered-By: PHP/7.1.33-16+0~20200514.38+debian9~1.gbp1e5820

{"data":[{"items":[{"metrics":[{"value":627,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":627,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:vk","title":"vk","icon":"https:\/\/favicon.yandex.net\/favicon\/vk.com"}},"isHasChild":0},{"metrics":[{"value":0,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":0,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"визитка","title":"визитка","icon":""}},"isHasChild":0},{"metrics":[{"value":10118,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":10118,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"","title":"Прямые визиты","icon":"https:\/\/cloud.roistat.com\/img\/arrow-right.png"}},"isHasChild":0},{"metrics":[{"value":10,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":10,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:mom.life","title":"mom.life","icon":""}},"isHasChild":0},{"metrics":[{"value":0,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":0,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"bot","title":"Роботы","icon":"https:\/\/cloud.roistat.com\/img\/r2d2.png"}},"isHasChild":0},{"metrics":[{"value":24,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":24,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:regmarkets","title":"regmarkets","icon":""}},"isHasChild":0},{"metrics":[{"value":2,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":2,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:glami","title":"glami","icon":""}},"isHasChild":0},{"metrics":[{"value":1,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":1,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:yp.ru","title":"yp.ru","icon":""}},"isHasChild":0},{"metrics":[{"value":50,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":50,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:email","title":"email","icon":"https:\/\/cloud.roistat.com\/img\/email.png"}},"isHasChild":0},{"metrics":[{"value":1022,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":1022,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"yamarket8","title":"Яндекс.Маркет","icon":"https:\/\/favicon.yandex.net\/favicon\/market.yandex.ru"}},"isHasChild":0},{"metrics":[{"value":4460,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":4460,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:convead","title":"convead","icon":""}},"isHasChild":0},{"metrics":[{"value":24,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":24,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:fb","title":"fb","icon":"https:\/\/favicon.yandex.net\/favicon\/facebook.com"}},"isHasChild":0},{"metrics":[{"value":9226,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":9226,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:admitad","title":"admitad","icon":""}},"isHasChild":0},{"metrics":[{"value":1,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":1,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:criteo","title":"criteo","icon":""}},"isHasChild":0},{"metrics":[{"value":42,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":42,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:source:u:youtube","title":"source_youtube","icon":"https:\/\/favicon.yandex.net\/favicon\/youtube.com"}},"isHasChild":0},{"metrics":[{"value":18,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":18,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:alpfederation","title":"alpfederation","icon":""}},"isHasChild":0},{"metrics":[{"value":238,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":238,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"unmarked","title":"Неразмеченные объявления","icon":""}},"isHasChild":0},{"metrics":[{"value":1,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":1,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":openstat:bwfya2v0lnlhbmrlec5ydtvqotgd0ydqungb0ylqungh0lxrgdc60ldrjydqv9c-0yhrg9c00lags292zwegrxnjyxblozbqn1zkz25hynjqqzbrwwfhag9dmgc7","title":"bwfya2v0lnlhbmrlec5ydtvqotgd0ydqungb0ylqungh0lxrgdc60ldrjydqv9c-0yhrg9c00lags292zwegrxnjyxblozbqn1zkz25hynjqqzbrwwfhag9dmgc7","icon":""}},"isHasChild":0},{"metrics":[{"value":0,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":0,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"unknown","title":"Нет значения","icon":""}},"isHasChild":0},{"metrics":[{"value":1,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":1,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:propartner:u:ru","title":"propartner_ru","icon":""}},"isHasChild":0},{"metrics":[{"value":23,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":23,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:baskru","title":"baskru","icon":""}},"isHasChild":0},{"metrics":[{"value":3,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":3,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:yell.ru","title":"yell.ru","icon":""}},"isHasChild":0},{"metrics":[{"value":44471,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":44471,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"seo","title":"SEO","icon":"https:\/\/cloud.roistat.com\/img\/MagnifyingGlass.png"}},"isHasChild":0},{"metrics":[{"value":1309,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":1309,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"marketplace","title":"marketplace","icon":""}},"isHasChild":0},{"metrics":[{"value":1,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":1,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"google10","title":"google","icon":"https:\/\/cloud.roistat.com\/img\/engines\/ga.png"}},"isHasChild":0},{"metrics":[{"value":1,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":1,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":utm:nativerent","title":"nativerent","icon":""}},"isHasChild":0},{"metrics":[{"value":2,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":2,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":":openstat:market.yandex.ru","title":"market.yandex.ru","icon":""}},"isHasChild":0},{"metrics":[{"value":13692,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":13692,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":{"marker_level_1":{"value":"site","title":"Визиты с сайтов","icon":"https:\/\/cloud.roistat.com\/img\/globe.png"}},"isHasChild":0}],"mean":{"metrics":[{"value":85367,"formatted":null,"metric_name":"visits","attribution_model_id":"default"},{"value":85367,"formatted":null,"metric_name":"visitCount","attribution_model_id":"default"}],"dimensions":[],"isHasChild":0},"dateFrom":"2020-10-01T00:00:00+0000","dateTo":"2020-11-01T00:00:00+0000","unprocessed":{"visits":0,"leads":0}}],"status":"success"}
```
So it seems the problem in HTTPie. Is it possible to handle with it?

**Comment by jakubroztocil** [comment]
@ab-kily could you please share the entire output when you run the command with `--debug`?

**Comment by ab-kily** [comment]
@jakubroztocil sorry for late answer. Here is the output:
```shell
HTTPie 2.3.0
Requests 2.22.0
Pygments 2.6.1
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
/usr/bin/python3
Linux 5.4.0-58-generic

<Environment {'colors': 256,
 'config': {'__meta__': {'about': 'HTTPie configuration file',
                         'help': 'https://httpie.org/doc#config',
                         'httpie': '1.0.3'},
            'default_options': []},
 'config_dir': PosixPath('/home/bagger/.httpie'),
 'devnull': <property object at 0x7f36ad145180>,
 'is_windows': False,
 'log_error': <function Environment.log_error at 0x7f36ad147280>,
 'program_name': 'http',
 'stderr': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
 'stderr_isatty': False,
 'stdin': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>,
 'stdin_encoding': 'utf-8',
 'stdin_isatty': True,
 'stdout': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>,
 'stdout_encoding': 'utf-8',
 'stdout_isatty': False}>

>>> requests.request(**{'auth': None,
 'data': '{"dimensions": ["marker_level_1"], "period": {"from": "2020-10-01", '
         '"to": "2020-11-01"}, "metrics": ["visits"]}',
 'headers': {'User-Agent': b'HTTPie/2.3.0', 'Accept': b'application/json, */*;q=0.5', 'Content-Type': b'application/json'},
 'method': 'post',
 'params': <generator object MultiValueOrderedDict.items at 0x7f36ace45580>,
 'url': 'https://cloud.roistat.com/api/v1/project/analytics/data?project=48526&key=xxx'})


http: error: ValueError: Elements in iterable body must be bytestrings. Illegal element: {

POST /api/v1/project/analytics/data?project=48526&key=xxx HTTP/1.1
User-Agent: HTTPie/2.3.0
Accept-Encoding: gzip, deflate
Accept: application/json, */*;q=0.5
Connection: keep-alive
Content-Type: application/json
Content-Length: 111
Host: cloud.roistat.com

{"dimensions": ["marker_level_1"], "period": {"from": "2020-10-01", "to": "2020-11-01"}, "metrics": ["visits"]}Traceback (most recent call last):
  File "/home/bagger/.local/lib/python3.8/site-packages/hyper/http11/connection.py", line 301, in _send_body
    self._sock.send(item)
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bagger/.local/bin/http", line 8, in <module>
    sys.exit(main())
  File "/home/bagger/.local/lib/python3.8/site-packages/httpie/__main__.py", line 11, in main
    exit_status = main()
  File "/home/bagger/.local/lib/python3.8/site-packages/httpie/core.py", line 79, in main
    exit_status = program(
  File "/home/bagger/.local/lib/python3.8/site-packages/httpie/core.py", line 196, in program
    for message in messages:
  File "/home/bagger/.local/lib/python3.8/site-packages/httpie/client.py", line 101, in collect_messages
    response = requests_session.send(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/bagger/.local/lib/python3.8/site-packages/hyper/contrib.py", line 74, in send
    conn.request(
  File "/home/bagger/.local/lib/python3.8/site-packages/hyper/common/connection.py", line 102, in request
    return self._conn.request(
  File "/home/bagger/.local/lib/python3.8/site-packages/hyper/http11/connection.py", line 187, in request
    self._send_body(body, body_type)
  File "/home/bagger/.local/lib/python3.8/site-packages/hyper/http11/connection.py", line 303, in _send_body
    raise ValueError(
ValueError: Elements in iterable body must be bytestrings. Illegal element: {

```

**Comment by Almad** [comment]
@ab-kily This looks like TLS issue. Would you mind running `openssl s_client -connect cloud.roistat.com:443` and posting it here?

**Comment by ab-kily** [comment]
@Almad , here it is:

```shell
bagger@bagger-work:~$ openssl s_client -connect cloud.roistat.com:443
CONNECTED(00000003)
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
verify return:1
depth=0 CN = *.roistat.com
verify return:1
---
Certificate chain
 0 s:CN = *.roistat.com
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
 1 s:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
   i:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
 2 s:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
   i:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGMjCCBRqgAwIBAgIQdGq81cIiGi6gduXV8APYxzANBgkqhkiG9w0BAQsFADCB
jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
MB4XDTIwMDUzMDAwMDAwMFoXDTIyMDUzMDIzNTk1OVowGDEWMBQGA1UEAwwNKi5y
b2lzdGF0LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANrmlsWI
ZXZVVsNvZHuDpkZoPFvZyMcHRrPg0lIcWG6wHdvAfR9tgASZ47S7hZG3NxCo7zke
8cA9fwkWtD/7RuFGiIq0uq0UGs3mUYyqwMNmaqYfusjBoDRm6dtOEv3klkxJqohB
o9mmF2ivWnaslbx/gHvUCNNWbOF8Ngw/OtFx0MX0VfwUL/94EmbPLG7rHxhM+6YB
hbCZSem5R20O2SsOGq5g/do8/HAJrDYTRymI5RnQ2JqgghP+yrkHnyzhDZZf3y2w
oOKfNvikbxMMPaEqe6TZQonWzJ0xP5cntRMWSmp9uZ3XDA8f+n0+3O5TiCKAIBtU
9tsxalRgWZjsPZUCAwEAAaOCAv4wggL6MB8GA1UdIwQYMBaAFI2MXsRUrYrhd+mb
+ZsF4bgBjWHhMB0GA1UdDgQWBBRN3MFwIiSlcbiIgnFmBD0hs9SUDDAOBgNVHQ8B
Af8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
BQUHAwIwSQYDVR0gBEIwQDA0BgsrBgEEAbIxAQICBzAlMCMGCCsGAQUFBwIBFhdo
dHRwczovL3NlY3RpZ28uY29tL0NQUzAIBgZngQwBAgEwgYQGCCsGAQUFBwEBBHgw
djBPBggrBgEFBQcwAoZDaHR0cDovL2NydC5zZWN0aWdvLmNvbS9TZWN0aWdvUlNB
RG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNydDAjBggrBgEFBQcwAYYX
aHR0cDovL29jc3Auc2VjdGlnby5jb20wJQYDVR0RBB4wHIINKi5yb2lzdGF0LmNv
bYILcm9pc3RhdC5jb20wggGABgorBgEEAdZ5AgQCBIIBcASCAWwBagB3AEalVet1
+pEgMLWiiWn0830RLEF0vv1JuIWr8vxw/m1HAAABcme8y4wAAAQDAEgwRgIhAK5H
RTFpRuILUJ3zeAUK6s7DB9fTGfKn7UYOXvffpGKyAiEAyU7OYLEzIdUa/v2oJT5j
v4fL0DQ58OtcbQRBvLJQJ5oAdwDfpV6raIJPH2yt7rhfTj5a6s2iEqRqXo47EsAg
RFwqcwAAAXJnvMu0AAAEAwBIMEYCIQDpJlVc0cQfVHoRcnIP2Q04+p/6l+DSp/KN
NdbfFGIEfwIhAMyzUQngMhTHQDl9jUMMjnMlempHHi25bqo4pfeNCJLgAHYAb1N2
rDHwMRnYmQCkURX/dxUcEdkCwQApBo2yCJo32RMAAAFyZ7zLhgAABAMARzBFAiEA
18fBvfeo48c4oUyS+Q5vouaQn+SIiyJAQFqXQI452wgCIEPcS/VnHGuGl+bMSzLn
6loE0h9xGbNJASUB3iLJKOffMA0GCSqGSIb3DQEBCwUAA4IBAQDJTvryCywsjRec
00C7waIcwXoRJhBPtop/KB1uosoaXMeEv+8mdmx+2aAh/0q13rQ1JoQdvj/Zm3On
0AaRQineJjwvXuZJodbmtRi+TNIaT2KwI0SCM4+4R87qNlYW+V4udMg1hAWgm/MY
k+rcRZ5SanV3BZ0HqonyZNqIYyyspVlFofzn40Cza7nyu/AWdOmx4zRy/sn90gCS
NoOCx4nMK3hYLglGvuTxDbR1ERnQKxnHFdc9BWt0opGmlQdGvpdC5jMV1SHU/2Jc
niF2YH8Vx5CtTMbmDo7YXpTVVaO4xBmSX5h1m6v/5mh4YGdPaYAsBfxsD+Nguqt7
BCR+nkUc
-----END CERTIFICATE-----
subject=CN = *.roistat.com

issuer=C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 5258 bytes and written 445 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 2E55203FFB22C30A5DFF667253E267B3BC374B7B8954F1933EBA500F777F9B4B
    Session-ID-ctx: 
    Master-Key: 7103ADAC2FF13A1F3B60635AC50933A649ED21F4C5A4B9CAA73BF2F99572C1E03B520504F32234FD8ED74D2DB66EC894
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 3600 (seconds)
    TLS session ticket:
    0000 - 50 48 e4 28 f5 02 d9 ad-e4 67 48 e4 08 00 3d 8b   PH.(.....gH...=.
    0010 - 14 e3 37 ef 79 7c 96 f1-f3 a3 bf 81 1e 41 c3 99   ..7.y|.......A..
    0020 - 69 4b 9d 08 31 20 9e 94-4b 8a c7 3f 2e a0 2f 37   iK..1 ..K..?../7
    0030 - c2 8e 61 1b 6e 91 e3 14-2f 9d 2c 66 06 6c 17 77   ..a.n.../.,f.l.w
    0040 - 81 71 ac 85 7c 13 f1 a0-00 3a e1 3b 41 9e 5e 2e   .q..|....:.;A.^.
    0050 - c9 c2 c4 8a 54 fa c0 cb-c5 9a 07 54 02 26 60 06   ....T......T.&`.
    0060 - 1e c2 3d a5 ff 56 f8 bb-c8 b4 31 11 4d 3b fb 99   ..=..V....1.M;..
    0070 - db b7 27 ec dd 1e cb f8-90 a3 59 23 1a 90 d1 bd   ..'.......Y#....
    0080 - 17 86 08 a0 55 2f 60 cf-8b 5f 49 58 16 0b 37 a7   ....U/`.._IX..7.
    0090 - f0 3f 1b d9 fa 04 ff 66-68 31 3f 02 7a 99 17 d3   .?.....fh1?.z...
    00a0 - b8 33 07 b7 7d 70 0a db-08 91 20 be 5f 29 29 aa   .3..}p.... ._)).
    00b0 - 9a 8a 66 a1 e0 51 6d 10-b5 d2 30 89 e0 70 7e 5a   ..f..Qm...0..p~Z

    Start Time: 1611575996
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

DONE
```

**Comment by Almad** [comment]
I unfortunately can't replicate—this needs further investigation

**Comment by BoboTiG** [comment]
@ab-kily what HTTPie plugins do you are using?

**Comment by ab-kily** [comment]
@BoboTiG how can I see list of plugins?

**Comment by BoboTiG** [comment]
Until #455 it will be hard to guess.

Maybe could you run that script and copy-paste the output?

```python
# file: list-plugins.py
from httpie.plugins.manager import PluginManager

plugin_manager = PluginManager()
plugin_manager.load_installed_plugins()
for plugin in plugin_manager:
    print(plugin.package_name, plugin)
```

Run it with `python3 list-plugings.py`.

**Comment by ab-kily** [comment]
@BoboTiG it seems I have no plugins installed:
```shell
$ cat test.py 
# file: list-plugins.py
from httpie.plugins.manager import PluginManager

plugin_manager = PluginManager()
plugin_manager.load_installed_plugins()
for plugin in plugin_manager:
    print(plugin.package_name, plugin)
$ python test.py 
$
```

**Comment by BoboTiG** [comment]
What give `python -V` & `python3 -V`?

**Comment by ab-kily** [comment]
@BoboTiG sorry, my previous message was wrong because I run the script on different server. So I run it on correct server and here is the output:
```shell
bagger-work:~$ cat test.py 
from httpie.plugins.manager import PluginManager

plugin_manager = PluginManager()
plugin_manager.load_installed_plugins()
for plugin in plugin_manager:
    print(plugin.package_name, plugin)
bagger-work:~$ python3 test.py 
httpie-http2 <class 'httpie_http2.HTTP2TransportPlugin'>
```
Python versions are:
```shell
bagger-work:~$ python -V && python3 -V
Python 3.8.11
Python 3.8.11
bagger-work:~$ 
```

Also, I update httpie to the latest version and the problem still exists:
```shell
bagger-work:~$ http --print hbHB POST  'https://cloud.roistat.com/api/v1/project/analytics/data?project=48526&key=XXX' dimensions:='["marker_level_1"]' period:='{"from": "2020-10-01","to": "2020-11-01"}' metrics:='["visits"]'
POST /api/v1/project/analytics/data?project=48526&key=XXX HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 111
Content-Type: application/json
Host: cloud.roistat.com
User-Agent: HTTPie/2.3.0

{
    "dimensions": [
        "marker_level_1"
    ],
    "metrics": [
        "visits"
    ],
    "period": {
        "from": "2020-10-01",
        "to": "2020-11-01"
    }
}



http: error: ValueError: Elements in iterable body must be bytestrings. Illegal element: {

bagger-work:~$ 
```

 I can send you API key in PM (there is nothing private), so you can check the problem by yourself.

**Comment by ab-kily** [comment]
@BoboTiG  I'm surprised there is no private message functionality in GitHub 😂😂😂

Here is an API key: `6554bfac99dbf6313ba552942c0f3b2d`

Just replace XXX by this key, and you should see the issue.

**Comment by BoboTiG** [comment]
(You could find my email ID on my profile.)

**Comment by BoboTiG** [comment]
(And you remove your comment, I have copied the key.)

**Comment by BoboTiG** [comment]
I can reproduce, thanks!

**Comment by BoboTiG** [comment]
The issue with HTTP/2 is more tricky than expected. We will fix everything at some point (see https://github.com/httpie/httpie/issues/692#issuecomment-646354697).

**Comment by isidentical** [comment]
I can no longer reproduce this issue (on a clean environment without any plugins). If it is still happening with the development revision, please let us know.
